# Generated by Django 6.0.3 on 2026-03-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='eventos/')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='productos/')),
                ('offset', models.BooleanField(default=False, help_text='Marcar para empujar la tarjeta hacia abajo en el diseño web')),
            ],
        ),
    ]
